class ENVIRONMENT:
  AIXP_USERNAME = 'AIXP_USERNAME'
  AIXP_USER = 'AIXP_USER'

  AIXP_PASSWORD = 'AIXP_PASSWORD'
  AIXP_PASS = 'AIXP_PASS'
  AIXP_PWD = 'AIXP_PWD'

  AIXP_HOSTNAME = 'AIXP_HOSTNAME'
  AIXP_HOST = 'AIXP_HOST'

  AIXP_PORT = 'AIXP_PORT'
