class ENVIRONMENT:
  AIXP_USERNAME = 'AIXP_USERNAME'
  AIXP_USER = 'AIXP_USER'
  EE_USERNAME = 'EE_USERNAME'

  AIXP_PASSWORD = 'AIXP_PASSWORD'
  AIXP_PASS = 'AIXP_PASS'
  AIXP_PWD = 'AIXP_PWD'
  EE_PASSWORD = 'EE_PASSWORD'

  AIXP_HOSTNAME = 'AIXP_HOSTNAME'
  AIXP_HOST = 'AIXP_HOST'
  EE_HOSTNAME = 'EE_HOSTNAME'

  AIXP_PORT = 'AIXP_PORT'
  EE_PORT = 'EE_PORT'
