class ENVIRONMENT:
  AIXP_USERNAME = 'AIXP_USERNAME'
  AIXP_USER = 'AIXP_USER'
  EE_USERNAME = 'EE_USERNAME'
  EE_USER = 'EE_USER'

  AIXP_PASSWORD = 'AIXP_PASSWORD'
  AIXP_PASS = 'AIXP_PASS'
  AIXP_PWD = 'AIXP_PWD'
  EE_PASSWORD = 'EE_PASSWORD'
  EE_PASS = 'EE_PASS'
  EE_PWD = 'EE_PWD'

  AIXP_HOSTNAME = 'AIXP_HOSTNAME'
  AIXP_HOST = 'AIXP_HOST'
  EE_HOSTNAME = 'EE_HOSTNAME'
  EE_HOST = 'EE_HOST'

  AIXP_PORT = 'AIXP_PORT'
  EE_PORT = 'EE_PORT'

  AIXP_CERT_PATH = 'AIXP_CERT_PATH'
  EE_CERT_PATH = 'EE_CERT_PATH'

  EE_SECURED = 'EE_SECURED'
  AIXP_SECURED = 'AIXP_SECURED'
