class FORMATTER_DATA:
  NAME = 'NAME'
  SIGNATURE = 'SIGNATURE'
  STREAM = 'STREAM'
  ID = 'ID'  # ??
  DESCRIPTION = 'DESCRIPTION'
  PLUGIN_INSTANCE_PARAMETER_LIST = 'PLUGIN_INSTANCE_PARAMETER_LIST'
